--  This file should contain the SQL to create a new TYPE called grocery and a new TABLE called shopping_list. 
-- The table will contain 6 columns and you will need to decide which SQL data types to use for each column. 

DROP TYPE IF EXISTS grocery;
CREATE TYPE GROCERY AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN default false NOT NULL,
    category grocery NOT NULL
);